# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=30)),
                ('private_directory', models.CharField(max_length=150)),
            ],
        ),
    ]
