# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20171209_0055'),
        ('terra', '0005_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('sNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('sNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terra.User')),
            ],
        ),
    ]
