# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0006_solve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solve',
            old_name='sNumber',
            new_name='sUser',
        ),
        migrations.RemoveField(
            model_name='solve',
            name='sNo',
        ),
    ]
