# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20171119_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='no',
            new_name='sNo',
        ),
    ]
