# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20171119_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
