# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terra', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=100)),
                ('grade', models.SmallIntegerField()),
                ('school', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
